router:
  epp:
    replicas: 1
    image:
      tag: v0.9.0
      pullPolicy: IfNotPresent
    resources:
      requests: {cpu: 100m, memory: 128Mi}
      limits: {cpu: 250m, memory: 256Mi}
  modelServers:
    matchLabels:
      app: mock-llm
      demo.kcd.io/model: demo-quality
    type: vllm
    protocol: http
    targetPorts:
      - number: 8080
  inferencePool:
    failureMode: FailClose
